dist: trusty
sudo: required

env:
  - releasever=27 basearch=x86_64

before_script:
  - sudo apt-get install -y mock
  - sudo groupadd mock
  - sudo usermod -a -G mock travis

script:
  - envsubst <templates/repo/fedora.repo >./fedora.repo && cat ./fedora.repo
  - sudo mv ./fedora.repo /etc/yum/repos.d/
  - sudo -E su $USER -c 'env'
  - sudo -E su $USER -c '/usr/bin/mock -r fedora-rawhide-x86_64 --init --resultdir=/home/$USER/results/'
