dist: trusty
sudo: required

before_script:
  - sudo apt-get install -y mock
  - sudo groupadd mock
  - sudo usermod -a -G mock travis

script:
- sudo -E su $USER -c 'mock -r fedora-rawhide-x86_64 --init'
