dist: trusty
sudo: required

language: c

services:
  - docker

script:
  - docker run -i --rm -v "$(pwd)":/results  --privileged toanju/lorax:27 /bin/bash <./create_container.sh
  - docker build -t fedora-min:latest .
