dist: trusty
sudo: required

before_script:
  - sudo apt-get install -y mock
  - sudo groupadd mock
  - sudo usermod -a -G mock travis

script:
- sudo -E su $USER -c 'env'
- sudo -E su $USER -c '/usr/bin/mock -r fedora-rawhide-x86_64 --init --resultdir=/home/$USER/results/'
